// Code generated by protoc-gen-go.
// source: packet.proto
// DO NOT EDIT!

/*
Package protocol is a generated protocol buffer package.

It is generated from these files:
	packet.proto

It has these top-level messages:
	Packet
*/
package protocol

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

// 	协议包
type Packet struct {
	Opcode           *int32  `protobuf:"varint,1,opt,name=opcode" json:"opcode,omitempty"`
	Name             *string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Module           *int32  `protobuf:"varint,3,opt,name=module" json:"module,omitempty"`
	Action           *int32  `protobuf:"varint,4,opt,name=action" json:"action,omitempty"`
	Data             []byte  `protobuf:"bytes,5,opt,name=data" json:"data,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Packet) Reset()         { *m = Packet{} }
func (m *Packet) String() string { return proto.CompactTextString(m) }
func (*Packet) ProtoMessage()    {}

func (m *Packet) GetOpcode() int32 {
	if m != nil && m.Opcode != nil {
		return *m.Opcode
	}
	return 0
}

func (m *Packet) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Packet) GetModule() int32 {
	if m != nil && m.Module != nil {
		return *m.Module
	}
	return 0
}

func (m *Packet) GetAction() int32 {
	if m != nil && m.Action != nil {
		return *m.Action
	}
	return 0
}

func (m *Packet) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
}
